### ISSUE TITLE
如何不使用php artisan serve开启 localhost:8000 直接使用虚拟域名访问扩展包里面的路由

### ISSUE THREAD

**Issue by liucg1995** [cviebrock/laravel5-package-template#3]
如何实现  域名/包设置的路由  进行访问

**Comment by cviebrock** [comment]
Courtesy of Google Translate:

> How do not use php artisan serve open localhost: 8000 direct access to the use of virtual domain expansion package inside the routing.
>
> How to achieve the domain name / package set the route to access

I'm sorry, but even with translation, I'm not sure I understand the question.

I would also add that I don't really maintain this package anymore.  There are probably many other Laravel 5 package templates out there that are better maintained than mine.
